apps/WebApp/Pages/Components/Footer/Default.cshtml.cs
// Clinical Skills Apps
// Copyright (c) bfren - licensed under https://mit.bfren.dev/2023

using System.Reflection;
using Jeebs.Apps.Web.Constants;
using Jeebs.Functions;
using Microsoft.AspNetCore.Mvc;

namespace WebApp.Pages.Components.Footer;

public sealed record class FooterModel(string Build, DateTime LastModified);

#if DEBUG
[ResponseCache(CacheProfileName = CacheProfiles.None)]
#else
[ResponseCache(CacheProfileName = CacheProfiles.Default)]
#endif
public sealed class FooterViewComponent : ViewComponent
{
	public async Task<IViewComponentResult> InvokeAsync() =>
		View(new FooterModel(
			Build: await VersionF.GetJeebsVersionAsync(),
			LastModified: File.GetLastWriteTime(Assembly.GetExecutingAssembly().Location)
		));
}

apps/WebApp/Pages/Components/Header/Default.cshtml.cs
// Clinical Skills Apps
// Copyright (c) bfren - licensed under https://mit.bfren.dev/2023

using Jeebs.Apps.Web.Constants;
using Microsoft.AspNetCore.Mvc;

namespace WebApp.Pages.Components.Header;

public sealed class Menu
{
	public readonly record struct Item(string Text, string Page);

	public IList<Item> Items { get; init; } = new List<Item>();

	public Menu() =>
		Items = new List<Item>
		{
			{ new("Entries", "/Entries/Index") },
			{ new("Profile", "/Auth/Profile") },
			{ new("Sign Out", "/Auth/Signout") }
		};
}

public sealed record class HeaderModel(Menu Menu);

#if DEBUG
[ResponseCache(CacheProfileName = CacheProfiles.None)]
#else
[ResponseCache(CacheProfileName = CacheProfiles.Default)]
#endif
public sealed class HeaderViewComponent : ViewComponent
{
	public IViewComponentResult Invoke() =>
		View(new HeaderModel(new()));
}

apps/WebApp/Pages/Components/Sidebar/Default.cshtml.cs
// Clinical Skills Apps
// Copyright (c) bfren - licensed under https://mit.bfren.dev/2023

using Microsoft.AspNetCore.Mvc;

namespace WebApp.Pages.Components.Sidebar;

public sealed class SidebarViewComponent : ViewComponent
{
	public IViewComponentResult Invoke() =>
		View();
}

apps/WebApp/Pages/Index.cshtml.cs
// Clinical Skills Apps
// Copyright (c) bfren - licensed under https://mit.bfren.dev/2023

using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebApp.Pages;

public sealed class IndexModel : PageModel { }

apps/WebApp/Pages/Index.cshtml
@page
@model WebApp.Pages.IndexModel

<!DOCTYPE html>
<html lang="en" class="h-100">
<head>

	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0" />
	<title>Clinical Skills</title>

	<!-- iOS meta -->
	<meta name="theme-color" content="#333" />
	<meta name="apple-mobile-web-app-capable" content="yes" />

	<!-- Style -->
	<environment names="Development">
		<link rel="stylesheet" href="~/css/bundles/1.0/clinical-skills-lib.css" />
		<link rel="stylesheet" href="~/css/bundles/1.0/clinical-skills.css" />
	</environment>
	<environment names="Staging,Production">
		<link rel="stylesheet" href="~/css/bundles/1.0/clinical-skills-lib.min.css" asp-append-version="true" />
		<link rel="stylesheet" href="~/css/bundles/1.0/clinical-skills.min.css" asp-append-version="true" />
	</environment>

	<!-- Script -->
	<script type="text/javascript" csp-add-nonce="true">
		var readyF = [];
		var ready = (f) => readyF.push(f);
		const home = "@Url.Page("/Entries/Index", "Home")";
		const sidebar = "@Url.Page("/Entries/Index", "Sidebar")";
		const signIn = "@Url.Page("/Auth/SignIn")";
		const auth = "jwt";
		const debug = true;
	</script>

</head>
<body class="d-flex flex-column h-100">

	<!-- Header -->
	<vc:header />

	<div class="container-fluid flex-shrink-0">

		<div class="row">

			<!-- Sidebar -->
			<vc:sidebar />

			<!-- Main Content -->
			<main role="main" id="content" class="col-12 col-md-9 col-xl-10 pt-3 px-md-4 flex-grow-1 w-100"></main>

		</div>

	</div>

	<!-- Footer -->
	<vc:footer />

	<!-- Script -->
	<environment names="Development">
		<script src="~/lib/font-awesome/js/all.js" data-auto-add-css="false"></script>
		<script src="~/js/bundles/clinical-skills-lib.js"></script>
		<script src="~/js/bundles/clinical-skills.js"></script>
	</environment>
	<environment names="Staging,Production">
		<script src="~/lib/font-awesome/js/all.min.js" data-auto-add-css="false" asp-append-version="true" csp-add-nonce="true"></script>
		<script src="~/js/bundles/clinical-skills-lib.min.js" asp-append-version="true" csp-add-nonce="true"></script>
		<script src="~/js/bundles/clinical-skills.min.js" asp-append-version="true" csp-add-nonce="true"></script>
	</environment>
	<script type="text/javascript" csp-add-nonce="true">
		readyF.forEach((f) => f());
	</script>

	<div id="create" class="fixed-bottom"></div>
	<div id="update" class="fixed-bottom"></div>
	<div id="delete" class="fixed-bottom"></div>

</body>
</html>